import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <head>
        <link href="/assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet"/>
  <link href="/assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet"/>
  <link href="/assets/vendor/aos/aos.css" rel="stylesheet"/>
  <link href="/assets/vendor/glightbox/css/glightbox.min.css" rel="stylesheet"/>
  <link href="/assets/vendor/swiper/swiper-bundle.min.css" rel="stylesheet"></link>
    </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
     

          <script defer src="assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script async src="/assets/vendor/php-email-form/validate.js"></script>
    <script async src="/assets/vendor/aos/aos.js"></script>
    <script async src="/assets/vendor/glightbox/js/glightbox.min.js"></script>
    <script async src="/assets/vendor/purecounter/purecounter_vanilla.js"></script>
    <script async src="/assets/vendor/imagesloaded/imagesloaded.pkgd.min.js"></script>
    <script async src="/assets/vendor/isotope-layout/isotope.pkgd.min.js"></script>
    <script async src="/assets/vendor/swiper/swiper-bundle.min.js"></script>

    <script defer src="assets/js/main.js"></script>
     </body>
    </html>
  );
}
